buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath 'com.anatawa12.forge:ForgeGradle:1.2-1.1.1'
    }
}

apply plugin: 'forge'

version = modVersion
group = "com.xiaomo305mua"
archivesBaseName = "MorphOptiFineCompat"

minecraft {
    version = minecraftVersion
    runDir = "eclipse"

    replaceIn "MOFCMod.java"
    replace "@modId@", modId
    replace "@modName@", modName
    replace "@modVersion@", modVersion
    replace "@modDependencies@", "required-after:" + modDependencies + ";"

    replaceIn "MOFCCoreMod.java"
    replace "@mcVersion@", project.minecraft.version.split('-')[0]
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    def p = { String k -> project.hasProperty(k) ? project.property(k) : "" }
    def mcModInfoProps = [
        'modId'           : p('modId'),
        'modName'         : p('modName'),
        'modDescription'  : p('modDescription'),
        'modVersion'      : p('modVersion'),
        'minecraftVersion': project.minecraft.version.split('-')[0],
        'modUrl'          : p('modUrl'),
        'authorList'      : p('authorList'),
        'credits'         : p('credits'),
        'logoFile'        : p('logoFile')
    ]

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand mcModInfoProps
    }
}

jar {
    manifest = project.manifest {
        attributes(
            'FMLCorePlugin': 'com.xiaomo305mua.morphoptifinecompat.MOFCCoreMod',
            'FMLCorePluginContainsFMLMod': 'true'
        )
    }
}